name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.3
  http: ^0.13.6
  http_parser: ^4.0.2
  logger: ^2.0.2
  cupertino_icons: ^1.0.8
  camera: ^0.10.0+4
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  geolocator: ^9.0.2
  path_provider: ^2.0.11
  path: ^1.8.3
  image_picker: ^0.8.7+3
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  google_sign_in: ^6.1.6    
  googleapis: ^12.0.0       
  googleapis_auth: ^1.4.1
  flutter_local_notifications: ^17.1.2
  image: ^3.0.2
  geocoding: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/profile.png
    - assets/images/1746000705093.jpeg
    - assets/images/pria.png
    - assets/images/priakiri.png
    - assets/images/wanitakiri.png
    - assets/images/wanita.png
    - assets/images/haiw.png
    - assets/images/hai.png
    - assets/images/logo2.png
    - assets/images/absen.png
    - assets/logo/logoapk.png
    - assets/images/baruuu.png
    - assets/images/baruuu copy.png
    - assets/images/bisa.png
    - assets/images/gagal.png

flutter_icons:
  android: true            
  ios: true                
  image_path: "assets/logo/logoapk.png"
